### ISSUE TITLE
Roadmap to 1.0

### ISSUE THREAD

**Issue by leouieda** [fatiando/fatiando#102]
So far, Fatiando releases have been kind of random. But now, I'd like to have a clear goal of things to work on for the future 1.0 release. The main thing we need for the major release is a more-or-less stable API. The new `fatiando.inversion` package was a step in this direction. Until we have this settled, we'll continue to release minor versions (0.3, 0.4, etc). This doesn't mean we can't work on other things as well, but this list will serve as a guide for setting priorities and open the discussion of our goals for the future.

We'll try to maintain a schedule of making a new release every **six months** to avoid piling up new features. This hopefully will make transitions easier as we break things moving forward.

To make things clear, I'm using [Semantic Versioning](http://semver.org/) for Fatiando. Quoting from the link:

> **How do I know when to release 1.0.0?**
> If your software is being used in production, it should probably already be 1.0.0. If you have a stable API on which users have come to depend, you should be 1.0.0. If you're worrying a lot about backwards compatibility, you should probably already be 1.0.0.
> **Doesn't this discourage rapid development and fast iteration?**
> Major version zero is all about rapid development. If you're changing the API every day you should either still be in version 0.y.z or on a separate development branch working on the next major version.

The key here is settling on a **stable API**. This means that:
- Package/module/function/class names shouldn't change
- Functions that do similar things should be called in a similar way (like the `solver.config(...).fit()` interface for **all** inversion code)
- The function/class signatures (how you call them and what arguments) shouldn't change

For all 1.\* releases, what is allowed is:
- Adding features that don't break old code
- Making old code more efficient **without** changing the interface
- Bug fixes 

With that in mind, here are the things that I'd like finished for the 1.0 release:
- [x] [PEP8](http://legacy.python.org/dev/peps/pep-0008/) compliance (Fixed in #115)
- [x] Have an example gallery (like [matplotlib](http://matplotlib.org/gallery.html)) to showcase nice figures (Done in #282)
- [ ] Tutorial section in docs (written in IPython notebooks?)
- [ ] More narrative documentation (guide with examples and text explaining how to work with Fatiando). Good examples are the [xarray docs](http://xarray.pydata.org/en/stable/) and the [keras docs](http://keras.io/)
- [ ] Clearly define a public API for Fatiando packages. Users should not see internal modules of each package (e.g. `from fatiando.gravmag.euler import EulerDeconv`) and non-public functions. Instead, all public classes/functions of a package should be importable from its root (e.g. `from fatiando import gravmag as gm; gm.EulerDeconv(...); gm.EQLGravity(...); gm.reduce_to_pole(...)`)
- [ ] Clean up, update or remove code that hasn't been touched and is not being used regularly
- [ ] Test coverage at least 90%
- [ ] Python 3 compatibility (#260)
- [ ] Make all code compatible with the new `inversion` package (#122, #123)
- [ ] At least one form of uncertainty estimation in `fatiando.inversion` (#121)
- [ ] Better interface for `seismic.wavefd` (#70)

**Update**: I removed a few that were more _feature requests_ than a must have for 1.0.

**Comment by leouieda** [comment]
Some progress on the documentation parts has been started in #266 and split into separate PRs (e.g. #282 )

**Comment by eusoubrasileiro** [comment]
@leouieda I guess we can mark done the Obspy part. Because, as we have discussed, Obspy integration is unnecessary .

What might be good to have is a cookbook or tutorial showing how to use Obspy and our plotting routines from `fatiando.vis`. I added a feature request [Issue 306](https://github.com/fatiando/fatiando/issues/306) I hope I did things right. I let to you to decide if its necessary for the 1.0 roadmap. 
I hope I did not do anything wrong...

**Comment by leouieda** [comment]
@eusoubrasileiro nothing wrong! Please keep providing feedback!
